site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - docker-web: nuevo.md

theme: 

  name: material

  palette:
    scheme: slate
    primary: green

  font:
    text: Teko

  language: es

  logo: images/logo.png

