site_name: IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - docker-web: nuevo.md
    - docker-web2: readme.md

theme: 

  name: material

  palette:
    scheme: slate
    primary: green

  font:
    text: Rajdhani

  language: es

  logo: /images/logo.png

